"""Trade sync model

Revision ID: 785d82e048d3
Revises: ec2d5822baa5
Create Date: 2026-07-04 23:34:09.053044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785d82e048d3'
down_revision: Union[str, Sequence[str], None] = 'ec2d5822baa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('broker', sa.String(), nullable=True))
    op.add_column('trades', sa.Column('ticket', sa.String(), nullable=True))
    op.add_column('trades', sa.Column('commission', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('swap', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('magic_number', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('trades', sa.Column('opened_at', sa.DateTime(), nullable=True))
    op.add_column('trades', sa.Column('closed_at', sa.DateTime(), nullable=True))
    op.add_column('trades', sa.Column('imported', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_trades_ticket'), 'trades', ['ticket'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_ticket'), table_name='trades')
    op.drop_column('trades', 'imported')
    op.drop_column('trades', 'closed_at')
    op.drop_column('trades', 'opened_at')
    op.drop_column('trades', 'comment')
    op.drop_column('trades', 'magic_number')
    op.drop_column('trades', 'swap')
    op.drop_column('trades', 'commission')
    op.drop_column('trades', 'ticket')
    op.drop_column('trades', 'broker')
    # ### end Alembic commands ###
